/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SupportedFeatures {
  keyboard: boolean
  images: boolean
  loadFrame: boolean
  compositeFrame: boolean
}
/** Enable features for the terminal that are necessary for Awrit */
export declare function termEnableFeatures(): SupportedFeatures
/** Disable previously enabled features for the terminal that are necessary for Awrit */
export declare function termDisableFeatures(features: SupportedFeatures): void
export interface DirtyRect {
  x: number
  y: number
  width: number
  height: number
}
export declare class ShmGraphicBuffer {
  /** Creates a new shared memory buffer with a unique name with the provided size */
  constructor(size: number)
  /** Returns the shared memory name as a base64 encoded string */
  get nameBase64(): string
  /** Creates and truncates the shared memory segment to the specified size, filling it with zeros */
  writeEmpty(): void
  /** Writes an image buffer to the shared memory at the specified dirty rectangle */
  write(buffer: Buffer, imageWidth: number, dirtyRect?: DirtyRect | undefined | null): void
}
