#!/bin/bash

set -e

BASE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE:-$0}")" &>/dev/null && pwd)
if [ ! -d "$BASE_DIR/node_modules" ]; then
    "$BASE_DIR/setup.sh"
fi

BUN="$BASE_DIR/.bun/bin/bun"
echo "shim" "$@" > "$BASE_DIR/awrit_error.txt"
exec -a awrit "$BUN" run ./src/runner "$@" 2>"$BASE_DIR/awrit_error.txt"